export const displayCharacters = [
  'JAM0SETENGAH',
  'SATU0DELAPAN',
  'DUABELASTIGA',
  'LIMASEMBILAN',
  'ENAM0SEPULUH',
  'TUJUHDELAPAN',
  'LIMA0SEBELAS',
  '0PAGI0SIANG0',
  '0SORE0MALAM0',
  '0KURANG0DUA0',
  'SEPULUH0LIMA',
  'BELAS0MENIT0',
];
